"""add webhooks table

Revision ID: 11f43cb9a1d4
Revises: 0012_add_keycloak_id
Create Date: 2026-04-16 18:21:09.317817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f43cb9a1d4'
down_revision: Union[str, Sequence[str], None] = '0012_add_keycloak_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
