"""Add performance indices

Revision ID: 194cd3ad999a
Revises: 57ae27e6411f
Create Date: 2026-03-06 22:47:27.301717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194cd3ad999a'
down_revision: Union[str, Sequence[str], None] = '57ae27e6411f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_components_is_deleted'), 'components', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_components_project_id'), 'components', ['project_id'], unique=False)
    op.create_index(op.f('ix_database_info_is_deleted'), 'database_info', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_database_info_project_id'), 'database_info', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_servers_is_deleted'), 'servers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_servers_project_id'), 'servers', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servers_project_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_is_deleted'), table_name='servers')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_database_info_project_id'), table_name='database_info')
    op.drop_index(op.f('ix_database_info_is_deleted'), table_name='database_info')
    op.drop_index(op.f('ix_components_project_id'), table_name='components')
    op.drop_index(op.f('ix_components_is_deleted'), table_name='components')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###
