"""add created_by to projects

Revision ID: 1e40dfd36939
Revises: 194cd3ad999a
Create Date: 2026-03-07 10:53:04.644427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e40dfd36939'
down_revision: Union[str, Sequence[str], None] = '194cd3ad999a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    # ### end Alembic commands ###
