"""Add uptime monitoring fields

Revision ID: 32bf8e06bbe1
Revises: 
Create Date: 2026-03-06 02:32:36.283737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bf8e06bbe1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('servers', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'last_checked_at')
    op.drop_column('servers', 'is_online')
    op.drop_column('projects', 'last_checked_at')
    op.drop_column('projects', 'is_online')
    # ### end Alembic commands ###
