"""Add soft delete columns

Revision ID: 57ae27e6411f
Revises: 427a215f5f18
Create Date: 2026-03-06 22:22:41.509460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ae27e6411f'
down_revision: Union[str, Sequence[str], None] = '427a215f5f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('components', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('database_info', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('database_info', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('servers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('servers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'deleted_at')
    op.drop_column('servers', 'is_deleted')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('database_info', 'deleted_at')
    op.drop_column('database_info', 'is_deleted')
    op.drop_column('components', 'deleted_at')
    op.drop_column('components', 'is_deleted')
    # ### end Alembic commands ###
